[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Agendas"
  url = "categories/agendas/"
  weight = -109

[[main]]
  name = "Minutes"
  url = "categories/minutes/"
  weight = -108

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Minutes"
#  identifier = "Minutes"
#  weight = -108
#[[main]]
#  parent = "Minutes"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Minutes"
#  name = "Twitter"
#  url = "https://twitter.com/"

#[[main]]
#  name = "About"
#  url = "about/"
#  weight = -107

# social menu links

#[[social]]
#  name = "github"
#  type = "social"
#  weight = 1
#  url = "https://github.com/#"
#[[social]]
#  name = "twitter"
#  weight = 2
#  url = "https://twitter.com/#"
#[[social]]
#  name = "linkedin"
#  weight = 3
#  url = "https://www.linkedin.com/in/#"
#[[social]]
#  name = "rss"
#  weight = 4
#  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
